apiVersion: v1
kind: Service
metadata:
  name: dblab-swagger-ui
  labels:
    app: dblab-swagger-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: dblab-swagger-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dblab-swagger-ui
  labels:
    app: dblab-swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dblab-swagger-ui
  template:
    metadata:
      labels:
        app: dblab-swagger-ui
    spec:
      containers:
        - name: dblab-swagger-ui
          image: $TAG
          imagePullPolicy: Always
