stages:
  - build

# Conditions.
.only_var_template: &only_tag_release
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^[0-9.]+$/

.only_var_template: &only_feature
  only:
    refs:
      - branches

# Jobs templates.
.job_template: &build_definition
  stage: build
  services:
    - docker:dind
  script:
    - apk add --no-cache bash
    - bash ./packages/ce/ci_docker_build_push.sh

# Jobs.
build_basic_image_release:
  <<: *build_definition
  <<: *only_tag_release
  variables:
    REGISTRY_USER: "${DH_CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${DH_CI_REGISTRY_PASSWORD}"
    REGISTRY: "${DH_CI_REGISTRY}"
    DOCKER_NAME: "postgresai/ce-ui"
    TAGS: "${DOCKER_NAME}:${CI_COMMIT_TAG},${DOCKER_NAME}:latest"

build_basic_image_dev:
  <<: *build_definition
  <<: *only_feature
  variables:
    REGISTRY_USER: "${CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${CI_REGISTRY_PASSWORD}"
    REGISTRY: "${CI_REGISTRY}"
    DOCKER_NAME: "registry.gitlab.com/postgres-ai/platform-web/ce-ui"
    TAGS: "${DOCKER_NAME}:${CI_COMMIT_REF_SLUG}"
  when: manual
