include:
  - local: 'ui/packages/ce/.gitlab-ci.yml'
  - local: 'ui/packages/platform/.gitlab-ci.yml'

.only_ui: &only_ui
  rules:
    - if: $CI_COMMIT_TAG =~ /^ui\/[0-9.]+$/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - ui/**/*
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - ui/**/*

.ui_cache: &ui_cache
  image: node:lts-alpine
  cache: &cache
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store
    policy: pull

check-code-style:
  <<: *only_ui
  <<: *ui_cache
  stage: test
  before_script:
    - apk add --no-cache curl
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir /builds/postgres-ai/database-lab/.pnpm-store/

  script:
    - pnpm --dir ui/ i
    - pnpm --dir ui/ --filter @postgres.ai/ce lint
    - pnpm --dir ui/ --filter @postgres.ai/platform lint
  interruptible: true
  cache:
    <<: *cache
    policy: push

semgrep-sast:
  stage: test
  image: returntocorp/semgrep
  <<: *only_ui
  <<: *ui_cache
  variables:
    # See more at semgrep.dev/explore.
    SEMGREP_RULES: >-
      p/security-audit
      p/secrets
      p/default
      p/owasp-top-ten
      p/javascript
      p/react
    # Upload findings to GitLab SAST Dashboard:
    SEMGREP_GITLAB_JSON: "1"
  script: semgrep ci --gitlab-sast > gl-sast-report.json || true
  artifacts:
    reports:
      sast: gl-sast-report.json
