include:
  - local: 'ui/packages/ce/.gitlab-ci.yml'
  - local: 'ui/packages/platform/.gitlab-ci.yml'

.only_ui: &only_ui
  rules:
    - if: $CI_COMMIT_TAG =~ /^ui\/[0-9.]+$/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - ui/**/*

check-code-style:
  <<: *only_ui
  stage: test
  image: node:16.13.0
  script:
    - npm --prefix ui/ ci -ws
    - npm --prefix ui/ run lint -w packages/ce
    - npm --prefix ui/ run lint -w packages/platform

semgrep-sast:
  stage: test
  image: returntocorp/semgrep
  <<: *only_ui
  variables:
    # See more at semgrep.dev/explore.
    SEMGREP_RULES: >-
      p/security-audit
      p/secrets
      p/default
      p/owasp-top-ten
      p/javascript
      p/react
    # Upload findings to GitLab SAST Dashboard:
    SEMGREP_GITLAB_JSON: "1"
  script: semgrep ci --gitlab-sast > gl-sast-report.json || true
  artifacts:
    reports:
      sast: gl-sast-report.json
